kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-container-storage-second
  annotations:
    volume.kubernetes.io/storage-class: glusterfs-storage-second
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
