---
ose_packages:
  - vim
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - dnsmasq
  - openshift-ansible-3.9.30-1.git.7.46f8678.el7.noarch
  - openshift-ansible-playbooks-3.9.30-1.git.7.46f8678.el7.noarch
  - openshift-ansible-roles-3.9.30-1.git.7.46f8678.el7.noarch
  - openshift-ansible-docs-3.9.30-1.git.7.46f8678.el7.noarch
  - atomic-openshift-utils-3.9.30-1.git.7.46f8678.el7.noarch
  - atomic-openshift-3.9.30-1.git.0.dec1ba7.el7.x86_64
  - atomic-openshift-excluder-3.9.30-1.git.0.dec1ba7.el7.noarch
  - atomic-openshift-docker-excluder-3.9.30-1.git.0.dec1ba7.el7.noarch
  - atomic-openshift-clients-3.9.30-1.git.0.dec1ba7.el7.x86_64

storage_packages:
  - nfs-utils
  - glusterfs-fuse
  - ceph-common
  - iscsi-initiator-utils
  - device-mapper-multipath

...
