apiVersion: v1
kind: Pod
metadata:
  name: qwiklab-test-pod
spec:
  containers:
    - name: qwiklab-test-containe
      image: docker.io/thoraxe/ocp-ops-cns-ci:0.1
      env:
        - name: HOME
          value: /tmp
        - name: QWIKLAB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: qwiklab-secret
              key: qwiklab-api-token
      imagePullPolicy: Always
  restartPolicy: Never
