---

  - name: install ose base packages
    yum: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - atomic-openshift-clients
      - atomic-openshift-utils
      - atomic-openshift-excluder
      - atomic-openshift-docker-excluder

  - name: install ose storage packages
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - glusterfs-fuse
      - ceph-common
      - iscsi-initiator-utils

  - name: remove openshift packages from filter
    shell: atomic-openshift-excluder unexclude

  - name: restart docker
    service: name=docker state=restarted


...
