---

  - name: enable EPEL
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

  - name: install aws-cfn-bootstrap dependencies
    yum: name={{ item }} state=present
    with_items:
      - python-pip
      - python-setuptools

  - name: disable hostname control in cloud-init
    lineinfile:
      regexp: '^ - {{ item }}'
      line: "{{ item }}"
      dest: /etc/cloud/cloud.cfg
      state: absent
    with_items:
      - set_hostname
      - update_hostname

...
