---

- name: temporarily enable epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: install utilities
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - jq
  - emacs
  - nano

- name: remove epel
  yum:
    name: epel-release
    state: absent

...
